language: swift

osx_image: xcode10

xcode_project: OpenWeatherMapKit.xcodeproj
xcode_scheme: OpenWeatherMapKit

script:
  - xcodebuild -project OpenWeatherMapKit.xcodeproj -scheme OpenWeatherMapKit -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=12.0' clean build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
